name: Release to NuGet

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1

      - name: Build
        run: dotnet build src/Avalonia.Stories/Avalonia.Stories.csproj -c Release -o out

      - name: Build solution and generate NuGet package
        run:  dotnet pack src/Avalonia.Stories/Avalonia.Stories.csproj  -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push out/*.nupkg --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json

      - name: Push Package to GitHub.com
        run: dotnet nuget push out/*.nupkg --skip-duplicate --no-symbols -k ${{ secrets.MY_TOKEN }} -s https://nuget.pkg.github.com/vzolotov/index.json
